# SITE SETTINGS
title: Ariel Ortiz-Bobea            # Title in top navigation bar (navbar) and <head>
author: Ariel Ortiz-Bobea               # Used for copyright statement in footer
#baseurl: "/aob.github.io"               # Only required if your site is in a directory e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                        # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/markdown/#links
remote_theme: peterdesmet/petridish


# COLORS
colors:
  links: "#b31b1b"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#b31b1b"                     # Background color for page banners: use color that contrasts well with white
  footer: "#f8f9fa"                     # Background color for footer: use color that contrasts well with white
font_serif: false                       # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons

# SOCIAL
social:
  email: ao332@cornell.edu
  googlescholar: MALB7wEAAAAJ           # Google Scholar user ID (from the URL of your profile)
  github: ArielOrtizBobea               # Can also be a github_username/repository
  bluesky: arielob.bsky.social
  twitter: ArielOrtizBobea
  linkedin: https://www.linkedin.com/in/ariel-ortiz-bobea-a904637/
  # mastodon: https://mastodon.social/@mastodon_username
  # facebook: https://www.facebook.com/groups/group_id/